"use client";

import Image from "next/image";
import Link from "next/link";
import { useI18n } from "@/lib/i18n/provider";
import { cn } from "@/lib/utils";

/**
 * Two artwork files, and CSS picks one.
 *
 * Reading the theme in JS would need a mounted flag — the server can't know the
 * mode — and that shows the wrong artwork for a frame on every load. The `dark`
 * class is already on <html> before first paint, so letting CSS decide is both
 * instant and flash-free.
 *
 * The PNGs have real alpha (generated by scripts/cutout-logos.py), so there is
 * no blend-mode trick here any more. That matters beyond tidiness: a blend mode
 * over the animated hero gradients would tint the artwork as the light drifted
 * underneath it.
 *
 * "full" is the whole lockup — drawing, CONTESSA, rule — and is driven by
 * width. "mark" is the crowned figure on its own, driven by height, because it
 * lives in a fixed-height bar.
 */

const ART = {
  full: { light: "/brand/logo-light.png", dark: "/brand/logo-dark.png", w: 1000, h: 989 },
  mark: { light: "/brand/emblem-light.png", dark: "/brand/emblem-dark.png", w: 512, h: 647 },
} as const;

export function Logo({
  variant = "full",
  className,
  priority = false,
}: {
  variant?: "full" | "mark";
  /** Set width for "full" (e.g. `w-40`), height for "mark" (e.g. `h-10`). */
  className?: string;
  priority?: boolean;
}) {
  const art = ART[variant];
  // object-contain plus one free axis: the whole drawing always fits, which is
  // the bug the old object-cover crop caused in the top bar.
  const shared = cn(
    "object-contain",
    variant === "mark" ? "w-auto" : "h-auto",
    className,
  );

  return (
    <>
      <Image
        src={art.light}
        alt="Contessa"
        width={art.w}
        height={art.h}
        priority={priority}
        className={cn(shared, "dark:hidden")}
      />
      <Image
        src={art.dark}
        alt="Contessa"
        width={art.w}
        height={art.h}
        priority={priority}
        className={cn(shared, "hidden dark:block")}
      />
    </>
  );
}

export function LogoLockup({ className }: { className?: string }) {
  const { t } = useI18n();

  return (
    <Link
      href="/"
      aria-label={t("nav.home")}
      className={cn("group flex items-center gap-2.5", className)}
    >
      {/* Height-driven so the emblem sits inside the bar whole, with room to
          breathe above and below rather than being cropped to fill it. */}
      <Logo variant="mark" className="h-9 shrink-0 sm:h-11" priority />
      <span className="flex flex-col leading-none">
        {/* Always Latin: the wordmark is the brand, not translated copy. */}
        <span className="font-display text-[1.05rem] tracking-luxe text-ink transition-colors group-hover:text-accent sm:text-xl">
          Contessa
        </span>
        <span className="mt-1 hidden text-[0.5rem] tracking-luxe-sm text-muted sm:block">
          {t("hero.tagline")}
        </span>
      </span>
    </Link>
  );
}
